//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULTRAMAVERICK.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MaverickReports")]
        public string rpt_path {
            get {
                return ((string)(this["rpt_path"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MaverickReports")]
        public string fdg {
            get {
                return ((string)(this["fdg"]));
            }
            set {
                this["fdg"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KABAYONGPROGRAM\\MSSQLSERVERMIS;Initial Catalog=UltraMaverickDB;Integr" +
            "ated Security=SSPI;")]
        public string hr_application_conn2 {
            get {
                return ((string)(this["hr_application_conn2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KABAYONGPROGRAM\\MSSQLSERVERMIS;Initial Catalog=UltraMaverickDB;Integr" +
            "ated Security=SSPI;")]
        public string hr_application_conn {
            get {
                return ((string)(this["hr_application_conn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KABAYONGPROGRAM\\MSSQLSERVERMIS;Initial Catalog=UltraMaverickDB;Integr" +
            "ated Security=SSPI;")]
        public string UltraMaverickDBConnectionString {
            get {
                return ((string)(this["UltraMaverickDBConnectionString"]));
            }
        }
    }
}
